############################
## CHANGE THESE
############################

baseURL: "https://hasifjalil.github.io/hugo"
title: hugo

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
